// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPZlFvqKxwnpacHddB7hTcNqRVmhzhuo',
    appId: '1:76122981368:web:0866ea497029e8bc800c0d',
    messagingSenderId: '76122981368',
    projectId: 'ecommerce-4d9f6',
    authDomain: 'ecommerce-4d9f6.firebaseapp.com',
    storageBucket: 'ecommerce-4d9f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2vF7-3ocDUJV7lfOL7aOecIjzFMQnAM',
    appId: '1:76122981368:android:35035032ce9d61a9800c0d',
    messagingSenderId: '76122981368',
    projectId: 'ecommerce-4d9f6',
    storageBucket: 'ecommerce-4d9f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdskLxMzMcJB__bcEXxDAGk-YWvqD63ho',
    appId: '1:76122981368:ios:aa663a52a53bf26e800c0d',
    messagingSenderId: '76122981368',
    projectId: 'ecommerce-4d9f6',
    storageBucket: 'ecommerce-4d9f6.appspot.com',
    iosBundleId: 'com.example.eCommerceUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdskLxMzMcJB__bcEXxDAGk-YWvqD63ho',
    appId: '1:76122981368:ios:aa663a52a53bf26e800c0d',
    messagingSenderId: '76122981368',
    projectId: 'ecommerce-4d9f6',
    storageBucket: 'ecommerce-4d9f6.appspot.com',
    iosBundleId: 'com.example.eCommerceUsingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEPZlFvqKxwnpacHddB7hTcNqRVmhzhuo',
    appId: '1:76122981368:web:8bf735953d4289db800c0d',
    messagingSenderId: '76122981368',
    projectId: 'ecommerce-4d9f6',
    authDomain: 'ecommerce-4d9f6.firebaseapp.com',
    storageBucket: 'ecommerce-4d9f6.appspot.com',
  );
}
